Template Update
Clan-ArgA/template-basico pull request #33
Opened 2024-04-28 02:14 UTC by NicolasAR99

Refloated a feature to directly add images and a text directly from the arga settings.

2024-04-28 19:54 UTC, IgnacioKase requested changes
The intent here is good, but we improve this by creating only one variable for intel images:

On `arga_settings.hpp`, you need just one variable. Let's name it `INTEL_IMAGES`. This variable could be an Array formatted like this:

```sqf

INTEL_IMAGES = [
    [IMAGE_1_NAME, IMAGE_1_CAPTION],
    [IMAGE_2_NAME, IMAGE_2_CAPTION],
    [IMAGE_3_NAME, IMAGE_3_CAPTION],
];
```

Note that the above is just an example, on arga_settings you just need to write an empty array: `INTEL_IMAGES = []`;

Then, on `fnc_setBriefing.sqf` iterate over the array to set the images using [forEach](https://community.bistudio.com/wiki/forEach).

2024-04-28 19:54 UTC, IgnacioKase commented on arga_settings.hpp
> +
Check lines 109 to 120. That's the section for constants related to the briefing (like these ones). Move these (or the new constants) to that section, please!

2024-05-21 19:24 UTC, IgnacioKase requested changes

2024-05-21 19:24 UTC, IgnacioKase commented on arga_settings.hpp
> +INTEL = [["imgs\logo.paa", "Imagen 1"], ["imgs\logo.paa", "Imagen 2"]];
remove the example lines, please!

it should be `INTEL = [];`

2024-05-21 19:24 UTC, IgnacioKase commented on core/private_settings.hpp
> +TEMPLATE_VERSION     = "0.9.23";
update the date as well please!

2024-06-22 22:22 UTC, NicolasAR99 commented
+ Forgot to add, last update also changed FONT and FONT Size for new intel so it would increase accesibility as inbefore was small and thin

2024-06-23 12:25 UTC, VulturARG requested changes

2024-06-23 12:25 UTC, VulturARG commented on core/scripts/assignRol.sqf
> +assignEngiPermission = {
What is Engi?
Do not use abbreviations in variable names

2024-06-23 12:25 UTC, VulturARG commented on core/scripts/assignRol.sqf
> +[] spawn assignEngiPermission;
Always leave a blank line at the end of the files.

2024-06-23 12:25 UTC, VulturARG commented on core/scripts/checkMedic.sqf
> +        if (_playerRoleDescription find "dic" != -1) then {
When searching for such a short string like **dic**, it is possible that someone will invent a name that includes it. I have seen any type of name in the missions, especially unofficial ones.

2024-06-23 12:25 UTC, VulturARG commented on core/scripts/checkMedic.sqf
> +        _AceInge = 2;
**_AceInge**: The same as before. Use complete words in English.

2024-06-23 12:25 UTC, VulturARG commented on core/scripts/checkMedic.sqf
> +[] spawn assignEngiPermission;
Last empty line missing

2024-06-25 08:16 UTC, IgnacioKase approved these changes

2025-02-16 12:47 UTC, VulturARG requested changes

2025-02-16 12:47 UTC, VulturARG commented on core/private_settings.hpp
> +TEMPLATE_LAST_UPDATE = "2025-02-16";                  // Escribir la fecha en formato AAAA-M-D sin ceros en el mes o el día.
Lee el comentario que tenés a la derecha

2025-02-17 15:41 UTC, VulturARG requested changes

2025-02-17 15:41 UTC, VulturARG commented on core/scripts/get_combat_role_clientside.sqf
> +    missionNamespace setVariable ["GVAR_ARGAIndexTardios", _IndexTardios + 1, true];
Para mantener una uniformidad de criterio, se usan todos los nombres de variable en inglés. Hay varios casos donde hay mezcla de idiomas o están los nombres de variables en español.

2025-02-18 12:26 UTC, VulturARG approved these changes

2025-02-18 20:11 UTC, merged